apiVersion: v1
kind: Service
metadata:
  name: building-apps-svc
  labels:
    app: kubeskills
spec:
  selector:
    app: kubeskills
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

